/**
 * The `<harness>-gate` wrapper.
 *
 * It runs the original binary (or a patched build, when one exists) with our
 * plugin merged in through the config-content env var — OPENCODE_* for
 * opencode, KILO_* for kilo, which do NOT overlap. The user's real config file
 * is never touched: the overlay is the single source of our additions, so
 * uninstall is just deleting this file.
 */
import fs from "node:fs"
import path from "node:path"
import type { Detected } from "./detect.ts"
import { PLUGIN_SPEC } from "./paths.ts"

export type WrapperOptions = {
  binDir: string
  /** Path (or npm spec) the harness loads the plugin from. */
  pluginSpec?: string
  /** TUI plugin, loaded through our own tui config so the stock binary stays clean. */
  tuiSpec?: string
  /** Where that generated tui config is written. */
  tuiConfigPath?: string
  /** The binary the wrapper execs: a patched build if present, else the original. */
  targetBinary: string
  guardUrl: string
  token?: string
  profileId?: string
}

export function wrapperPath(binDir: string, id: string): string {
  return path.join(binDir, `${id}-gate`)
}

/**
 * The guard is addressed through the environment, not through plugin options.
 *
 * Both wrapper kinds now say it the same way, and both let an explicit
 * AGENTGATE_URL win — which is what makes recording, staging and a quick
 * point-at-a-different-guard possible without reinstalling.
 *
 * Plugin options were the original route and were silently a no-op: the key
 * written was `guardUrl` while the config reads `url`, so the address never
 * arrived and the plugin fell back to localhost. A gate pointed at nothing
 * fails open, so this looked exactly like a working install.
 */
export function renderWrapper(target: Detected, options: WrapperOptions): string {
  const overlay: Record<string, unknown> = {
    plugin: [[options.pluginSpec ?? PLUGIN_SPEC, {}]],
  }
  const contentVar = `${target.envPrefix}_CONFIG_CONTENT`
  const disableVar = `${target.envPrefix}_DISABLE_AUTOUPDATE`
  const tuiVar = `${target.envPrefix}_TUI_CONFIG`
  const json = JSON.stringify(overlay)

  const lines = [
    "#!/bin/sh",
    "# Generated by @agentgate/gate. Delete this file to uninstall the wrapper.",
    `export ${disableVar}=1`,
    // Single-quote the JSON for the shell; it contains no single quotes.
    `export ${contentVar}='${json}'`,
    `export AGENTGATE_URL="\${AGENTGATE_URL:-${options.guardUrl}}"`,
  ]
  if (options.token) lines.push(`export AGENTGATE_TOKEN="\${AGENTGATE_TOKEN:-${options.token}}"`)
  if (options.profileId) lines.push(`export AGENTGATE_PROFILE="\${AGENTGATE_PROFILE:-${options.profileId}}"`)
  // The badge and Shift+Tab must appear only under the wrapper. Writing them
  // into the shared tui config would give the untouched binary a "gate: auto"
  // badge while nothing is actually gated — a lie about being protected.
  if (options.tuiConfigPath) lines.push(`export ${tuiVar}=${shellQuote(options.tuiConfigPath)}`)
  lines.push(`exec ${shellQuote(options.targetBinary)} "$@"`, "")
  return lines.join("\n")
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`
}

export function writeWrapper(target: Detected, options: WrapperOptions): string {
  const file = wrapperPath(options.binDir, target.id)
  fs.mkdirSync(options.binDir, { recursive: true })
  fs.writeFileSync(file, renderWrapper(target, options))
  fs.chmodSync(file, 0o755)
  return file
}

export function removeWrapper(binDir: string, id: string): boolean {
  const file = wrapperPath(binDir, id)
  if (!fs.existsSync(file)) return false
  fs.rmSync(file)
  return true
}

export type HomeWrapperOptions = {
  binDir: string
  /**
   * Env var that relocates the harness's whole config directory. Absent for
   * harnesses that select behaviour another way — dsh uses `--profile gate`.
   */
  homeEnvVar?: string
  /** Directory we own, prepared with our plugin registered. */
  homeDir?: string
  guardUrl: string
  token?: string
  profileId?: string
  /** Extra arguments the wrapper always passes (dsh needs `--profile gate`). */
  extraArgs?: string[]
}

/**
 * Wrapper for harnesses that keep everything in one directory (Codex, Pi) or
 * select behaviour by profile (dsh). Instead of editing the user's config we
 * point the harness at a directory of our own, so `codex` and `codex-gate` are
 * genuinely different programs to run rather than one program in two states.
 *
 * The guard URL is defaulted, not forced: an explicit AGENTGATE_URL in the
 * environment still wins, which is what makes recording and staging possible.
 */
export function renderHomeWrapper(id: string, options: HomeWrapperOptions): string {
  const lines = [
    "#!/bin/sh",
    "# Generated by @agentgate/gate. Delete this file to uninstall the wrapper.",
  ]
  if (options.homeEnvVar && options.homeDir) {
    lines.push(`export ${options.homeEnvVar}=${shellQuote(options.homeDir)}`)
  }
  lines.push(`export AGENTGATE_URL="\${AGENTGATE_URL:-${options.guardUrl}}"`)
  if (options.token) lines.push(`export AGENTGATE_TOKEN="\${AGENTGATE_TOKEN:-${options.token}}"`)
  if (options.profileId) lines.push(`export AGENTGATE_PROFILE="\${AGENTGATE_PROFILE:-${options.profileId}}"`)
  const args = (options.extraArgs ?? []).map(shellQuote).join(" ")
  lines.push(`exec ${id} ${args} "$@"`.replace(/\s+/g, " ").trim(), "")
  return lines.join("\n")
}

export function writeHomeWrapper(id: string, options: HomeWrapperOptions): string {
  const file = wrapperPath(options.binDir, id)
  fs.mkdirSync(options.binDir, { recursive: true })
  fs.writeFileSync(file, renderHomeWrapper(id, options))
  fs.chmodSync(file, 0o755)
  return file
}
