/**
 * The `<harness>-gate` wrapper.
 *
 * It runs the original binary (or a patched build, when one exists) with our
 * plugin merged in through the config-content env var — OPENCODE_* for
 * opencode, KILO_* for kilo, which do NOT overlap. The user's real config file
 * is never touched: the overlay is the single source of our additions, so
 * uninstall is just deleting this file.
 */
import fs from "node:fs"
import path from "node:path"
import type { Detected } from "./detect.ts"
import { PLUGIN_SPEC } from "./paths.ts"

export type WrapperOptions = {
  binDir: string
  /** The binary the wrapper execs: a patched build if present, else the original. */
  targetBinary: string
  guardUrl: string
  token?: string
  profileId?: string
}

export function wrapperPath(binDir: string, id: string): string {
  return path.join(binDir, `${id}-gate`)
}

export function renderWrapper(target: Detected, options: WrapperOptions): string {
  const overlay: Record<string, unknown> = {
    plugin: [[PLUGIN_SPEC, pluginOptions(options)]],
  }
  const contentVar = `${target.envPrefix}_CONFIG_CONTENT`
  const disableVar = `${target.envPrefix}_DISABLE_AUTOUPDATE`
  const json = JSON.stringify(overlay)

  return [
    "#!/bin/sh",
    "# Generated by @agentgate/gate. Delete this file to uninstall the wrapper.",
    `export ${disableVar}=1`,
    // Single-quote the JSON for the shell; it contains no single quotes.
    `export ${contentVar}='${json}'`,
    `exec ${shellQuote(options.targetBinary)} "$@"`,
    "",
  ].join("\n")
}

function pluginOptions(options: WrapperOptions): Record<string, unknown> {
  const opts: Record<string, unknown> = { guardUrl: options.guardUrl }
  if (options.token) opts.token = options.token
  if (options.profileId) opts.profileId = options.profileId
  return opts
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`
}

export function writeWrapper(target: Detected, options: WrapperOptions): string {
  const file = wrapperPath(options.binDir, target.id)
  fs.mkdirSync(options.binDir, { recursive: true })
  fs.writeFileSync(file, renderWrapper(target, options))
  fs.chmodSync(file, 0o755)
  return file
}

export function removeWrapper(binDir: string, id: string): boolean {
  const file = wrapperPath(binDir, id)
  if (!fs.existsSync(file)) return false
  fs.rmSync(file)
  return true
}
