"""API key generation, hashing, and the ``api_keys`` repository.

Design: docs/superpowers/service/specs/api-keys.md.

The plaintext key exists only for the instant between ``generate_key()`` and
the caller printing or returning it -- ``ApiKeyRepo.create`` hands it back
exactly once and stores only its SHA-256 hash. Nothing in this module logs a
plaintext key or a key hash; callers must not either (see
``agentgate/cli.py`` and ``agentgate/api/deps.py``).

Hashing is unsalted SHA-256, not a slow KDF: the key is generated by us with
32 bytes (256 bits) of ``secrets`` entropy, so there is no low-entropy
secret for a slow hash to protect against brute force, and a slow hash on
the verification hot path (stage 1's ~1ms budget) would be a self-inflicted
denial of service. See the spec's "Хэширование" section for the full
argument.
"""

import base64
import hashlib
import secrets
from dataclasses import dataclass
from datetime import datetime, timezone

from sqlalchemy import select
from sqlalchemy.ext.asyncio import async_sessionmaker
from ulid import ULID

from agentgate.domain.principal import ensure_key_id_shape
from agentgate.store.models import ApiKeyRow

KEY_PREFIX = "agk_"
_ENTROPY_BYTES = 32


def mint_key_id() -> str:
    """The public id of a new key: a ULID, checked before it leaves here.

    The id is the principal a decision is attributed to, and the static
    token's principal is a literal that no id may equal -- so the shape is
    checked where the id is born, not where it is read.
    """
    return ensure_key_id_shape(str(ULID()))


def generate_key() -> str:
    """Generate one plaintext API key: ``agk_`` + base64url(32 random bytes), no padding.

    Uses ``secrets.token_bytes``, not ``random`` -- the prefix identifies the
    key in logs and dumps and lets secret scanners (gitleaks, GitHub push
    protection) key on one pattern.
    """
    raw = secrets.token_bytes(_ENTROPY_BYTES)
    token = base64.urlsafe_b64encode(raw).rstrip(b"=").decode("ascii")
    return f"{KEY_PREFIX}{token}"


def hash_key(key: str) -> str:
    """SHA-256 hex digest of a plaintext key. This is the only form ever stored."""
    return hashlib.sha256(key.encode("utf-8")).hexdigest()


@dataclass
class ApiKeyRecord:
    id: str
    label: str
    created_at: datetime
    expires_at: datetime | None
    revoked_at: datetime | None
    last_used_at: datetime | None

    @classmethod
    def from_row(cls, row: ApiKeyRow) -> "ApiKeyRecord":
        return cls(
            id=row.id, label=row.label, created_at=row.created_at, expires_at=row.expires_at,
            revoked_at=row.revoked_at, last_used_at=row.last_used_at,
        )

    def is_valid(self, now: datetime | None = None) -> bool:
        """True if this key is neither revoked nor expired as of ``now``."""
        now = now if now is not None else datetime.now(timezone.utc)
        if self.revoked_at is not None:
            return False
        if self.expires_at is not None and self.expires_at <= now:
            return False
        return True


class ApiKeyRepo:
    """Repository for the ``api_keys`` table.

    Each method opens and commits its own session, matching the other
    repositories in ``agentgate.store.repo``.
    """

    def __init__(self, session_factory: async_sessionmaker) -> None:
        self._sf = session_factory

    async def create(self, label: str, expires_at: datetime | None = None) -> tuple[str, ApiKeyRecord]:
        """Mint a new key. Returns ``(plaintext_key, record)``.

        The plaintext is returned here and only here -- it is never
        persisted, logged, or recoverable afterwards. Only ``key_hash`` is
        written to the row.
        """
        plaintext = generate_key()
        key_hash = hash_key(plaintext)
        now = datetime.now(timezone.utc)
        row = ApiKeyRow(
            id=mint_key_id(), key_hash=key_hash, label=label, created_at=now,
            expires_at=expires_at, revoked_at=None, last_used_at=None,
        )
        async with self._sf() as s:
            s.add(row)
            await s.commit()
        return plaintext, ApiKeyRecord.from_row(row)

    async def get_by_hash(self, key_hash: str) -> ApiKeyRecord | None:
        """Look up a key by its SHA-256 hash. Returns ``None`` if no row matches.

        Does not filter on revocation or expiry -- callers check
        ``ApiKeyRecord.is_valid()`` themselves (see ``ApiKeyVerifier`` in
        ``agentgate.api.deps``), so a caller that wants to distinguish
        "never existed" from "revoked"/"expired" (e.g. for an audit tool)
        still can.
        """
        stmt = select(ApiKeyRow).where(ApiKeyRow.key_hash == key_hash)
        async with self._sf() as s:
            row = (await s.execute(stmt)).scalar_one_or_none()
        return ApiKeyRecord.from_row(row) if row is not None else None

    async def list(self) -> list[ApiKeyRecord]:
        """List all keys, newest first. Never includes the key or its hash."""
        stmt = select(ApiKeyRow).order_by(ApiKeyRow.created_at.desc())
        async with self._sf() as s:
            rows = (await s.execute(stmt)).scalars().all()
        return [ApiKeyRecord.from_row(r) for r in rows]

    async def revoke(self, key_id: str) -> bool:
        """Soft-revoke by id: set ``revoked_at`` if unset. Returns whether the id exists.

        The row is never deleted -- see the spec's "Хранение" section: a
        deleted key is indistinguishable from one that never existed, and an
        incident review needs to know a key existed and when it was cut off.
        """
        async with self._sf() as s:
            row = await s.get(ApiKeyRow, key_id)
            if row is None:
                return False
            if row.revoked_at is None:
                row.revoked_at = datetime.now(timezone.utc)
                await s.commit()
            return True

    async def touch_last_used(self, key_id: str) -> None:
        """Record that a key was just used. Called after the response is sent."""
        async with self._sf() as s:
            row = await s.get(ApiKeyRow, key_id)
            if row is not None:
                row.last_used_at = datetime.now(timezone.utc)
                await s.commit()
