"""Regenerate ../contracts/openapi.yaml from the pydantic models.

The schema components under ``components.schemas`` are GENERATED from
``agentgate.api.schemas`` and ``agentgate.profiles.schema`` — never hand
written — so they cannot drift from the code. Only prose (endpoint and
field descriptions, examples) is authored here.

Field descriptions are applied as an overlay keyed by field name; an
overlay key that no longer exists on the model raises, so removing or
renaming a field breaks this exporter instead of silently leaving a
stale description in the published contract.

Run:  cd service && uv run python scripts/export_openapi.py
Test: tests/test_contracts.py asserts the committed YAML equals the
      freshly generated document.
"""

import copy
import importlib.metadata
from pathlib import Path
from typing import Any

import yaml
from pydantic.json_schema import models_json_schema

from agentgate.api.schemas import (
    METADATA_MAX_BYTES,
    RAW_MAX_BYTES,
    USER_REQUEST_MAX_CHARS,
    DecideRequest,
    DecideResponse,
)
from agentgate.profiles.schema import Profile

CONTRACTS = Path(__file__).resolve().parents[2] / "contracts"
OUTPUT = CONTRACTS / "openapi.yaml"

HEADER = """\
# Generated by service/scripts/export_openapi.py — do not edit by hand.
# The schema components come from the pydantic models in
# service/agentgate/api/schemas.py and service/agentgate/profiles/schema.py.
# Regenerate:  cd service && uv run python scripts/export_openapi.py
# service/tests/test_contracts.py fails if this file and the models disagree.
"""

# --------------------------------------------------------------------------
# Prose
# --------------------------------------------------------------------------

API_DESCRIPTION = f"""\
AgentGate is a harness-agnostic gate for coding-agent actions. A harness calls
`POST /v1/decide` from its pre-tool-use hook with one proposed action and the
user's last message; the service answers `allow`, `deny` or `ask` after a
two-stage cascade (deterministic stage 1, then an LLM classifier as stage 2).

## The five things an integrator must get right

**1. Every decision is HTTP 200 — including refusals.** `deny` and `ask` are
values of `decision` in the response body, never HTTP error statuses. A client
that treats a non-2xx status as "denied" misreads this contract. The only
non-200 status the service returns on purpose is `401` for a missing or wrong
bearer token.

**2. The service is fail-closed: every failure resolves to `ask`.** An invalid
request body, an unknown `tool`, an exceeded size limit, an unparseable
command, an LLM timeout, an LLM error, an invalid LLM response, or an internal
error — all of them return HTTP 200 with `decision: "ask"` and a `reason`
explaining why. `allow` on error is impossible by design. A client must never
translate a transport failure, a timeout or an unparseable response into
`allow`; treat anything you cannot parse as `ask` and put the action in front
of the user.

**3. `deny` always carries `reason` and `suggest`.** There is no separate
"deny but continue" decision. On `deny` the caller renders `reason` back to the
model as the tool result (the wording template lives in
`contracts/deny_message_template.md`) and shows `suggest` — the safe
alternative — to the user. `suggest` is an empty string only when there is
nothing to suggest.

**4. Request limits are enforced by the models, and one of them is in bytes.**
`session_id` at most 128 characters; `harness` 1–64 characters; `raw` at most
{RAW_MAX_BYTES} **bytes** of UTF-8 — not characters, so Cyrillic text costs 2
bytes per character and a 20000-character Russian command is already over the
limit; `metadata` at most {METADATA_MAX_BYTES} bytes when serialized as JSON;
`user_request` is not rejected when too long but truncated server-side to
{USER_REQUEST_MAX_CHARS} characters **keeping the tail**, because the end of the
message is the part that describes the current task. Violating a hard limit is
not an error status — per rule 2 it comes back as `ask`.

**5. Policy lives on the server.** A harness knows only the service URL, the
bearer token and optionally a `profile_id`. It never sees, uploads or caches
policy. Two consequences: `args.paths` and `args.domains` are **ignored for
`tool: shell`** (the service extracts paths and domains itself from the
command's AST, so a client that sends them is not wrong, just ignored), and
`raw` is **required and non-blank for `tool: shell`** because the raw command
line is what stage 1 parses.

## Sessions

`session_id` is optional but load-bearing. With it, the service keeps
per-session counters (consecutive denials, a window over the last 50 outcomes)
that escalate a repeatedly blocked agent to `ask`, and an `allow` cache that
returns a previously granted identical action with `cached: true` and
`stage: 0`. Only `allow` is ever cached; `deny` and `ask` never are. Without a
`session_id` there are no counters and no cache, and the decision is recorded
with a null session.

## Implementation status

All four routes are implemented, tested and running in v1. `POST /v1/decide`,
`GET /v1/decisions`, `GET /v1/profiles/{{id}}` and `GET /healthz` are the settled
contract; the request/response schemas below are generated from the running
pydantic models. Integrate against these shapes.
"""

AUTH_DESCRIPTION = """\
`Authorization: Bearer <credential>`. The credential is EITHER the static
`AGENTGATE_TOKEN` (set in the service's environment) OR an issued API key. A
request authenticates if the bearer matches either one; both are checked in
constant time.

**API keys** are minted by the operator from the CLI, never over HTTP:
`python -m agentgate keys create --label <name>` (also `keys list`,
`keys revoke <key_id>`). A key is shown exactly once at creation, looks like
`agk_` followed by 43 URL-safe characters, and is stored only as a SHA-256 hash
— the plaintext is never persisted or logged. A revoked or expired key stops
working within a short in-process cache TTL (revocation is not instant, up to a
minute). Hand each integrator their own key so it can be revoked individually.

OpenAPI cannot express the conditional rule, so it is stated here: on a
non-localhost bind a credential is required (the service will not start without a
token, and issued keys are also accepted); on a localhost bind with no token and
no keys, every request passes (dev mode) — which is why the scheme is declared
optional in `security`. `GET /healthz` never requires a credential. A missing,
wrong, expired or revoked credential all return the same opaque HTTP 401 (the
body does not say which); every other failure is a 200 `ask`, not a 401.
"""

DECIDE_DESCRIPTION = """\
Decide on one proposed agent action. This is the call a harness makes from its
pre-tool-use hook (`PreToolUse` in Claude Code, `tool.execute.before` in
OpenCode) while the tool call is suspended.

The service normalizes the action, checks the allow cache, runs deterministic
stage 1, escalates to the stage-2 LLM classifier if stage 1 did not settle it,
applies session escalation, and answers. The whole exchange is one round trip
and one decision; there are no retries and no streaming.

**Always HTTP 200.** `deny` and `ask` come back as `decision` values with a 200
status. Invalid bodies, size-limit violations, unparseable commands, LLM
timeouts and internal errors all come back as HTTP 200 with `decision: "ask"`
— never as an error status and never as `allow`. The single non-200 the service
returns on purpose is 401 for a bad bearer token; if you receive anything else
(a 5xx from a proxy, a connection reset, a timeout), treat it as `ask` and ask
the user, never as `allow`.

**Per-tool requirements.** `raw` must be present and non-blank for
`tool: shell`. `args.paths` and `args.domains` are ignored for `shell` — the
service derives both from the command's syntax tree. `args.mcp` carries the
server, tool and arguments for `tool: mcp_call`.

**Reading the answer.** `stage` says who decided: `1` deterministic, `2` the
LLM, `0` a cache hit or an API-level refusal. `rule_id` names the stage-1 rule
(`hard-deny.exfil`, `profile.path`, `allowlist.readonly`, `escalation`, …) and
is `null` when stage 2 decided. `latency_ms` reports per stage, with `null` for
a stage that did not run. `decision_id` is a ULID and the primary key of the
stored decision — quote it in bug reports.

The request and response examples below are paired by name: `allow_safe_test`,
`deny_unknown_package`, `ask_uncertain_db_cleanup`. The fourth response example
has no request counterpart because it shows what an invalid request produces.
"""

DECISIONS_DESCRIPTION = """\
Decision feed for the dashboard and the benchmark. Returns stored decisions
newest first as `{items, next_before}`, with cursor pagination by `decision_id`:
pass the `next_before` from a page back as the `before` query parameter to get
the next (older) page. `next_before` is `null` when the last page was returned.
Because `decision_id` is a ULID, ordering by it is ordering by time.

`limit` is `1..500`, default `100`; a value outside that range is a `422`
(this is a read endpoint, not the always-200 decide path). Requires the bearer
credential when the service is configured with one.
"""

PROFILE_DESCRIPTION = """\
Reads a policy profile exactly as the service loaded it, returned as the
`Profile` object directly (200) or a `404` for an unknown id. The `Profile`
schema is generated from the running pydantic model
(`agentgate/profiles/schema.py`). Profiles are
server-side configuration: a harness passes at most a `profile_id` and never
reads policy in normal operation. This endpoint exists for operators and the
dashboard.

**Secrets are not returned.** Model API keys are never stored in a profile in
the first place — a profile holds only the *name* of the environment variable
(`api_key_env`), and that name is what comes back.
"""

HEALTH_DESCRIPTION = """\
Liveness probe, no credential required. Returns `{"status": "ok" | "degraded",
"db": <bool>, "llm": null}`: `status` is `degraded` when the database probe
fails, `ok` otherwise; `db` is the boolean result of that probe; `llm` is
reserved and currently always `null`. The status code is always `200` — a
`degraded` body, not a 5xx, signals a dependency is down. A single `/healthz`
right after a container start can briefly report `db: false` during connection
warmup and then recover.
"""

UNAUTHORIZED_DESCRIPTION = """\
Missing or invalid bearer token. This is the only status the service returns
on purpose instead of a decision — every other failure is a `200` with
`decision: "ask"`. The body shape is not fixed by the design spec.
"""

# --------------------------------------------------------------------------
# Field description overlays (keys are checked against the generated schemas)
# --------------------------------------------------------------------------

FIELD_DESCRIPTIONS: dict[str, dict[str, str]] = {
    "DecideRequest": {
        "session_id": (
            "Harness session identifier, at most 128 characters. Optional, but "
            "without it the service keeps no per-session counters and no allow "
            "cache, and the decision is stored with a null session."
        ),
        "harness": (
            "Free-form name of the calling harness: `opencode`, `claude-code`, "
            "`codex`, `kilo`, `bench`, … 1-64 characters."
        ),
        "tool": "Kind of action being gated.",
        "raw": (
            f"Raw payload as text. **Required and non-blank for `tool: shell`**, "
            f"where it is the command line stage 1 parses; for the other tools it "
            f"is the raw payload. At most {RAW_MAX_BYTES} **bytes** of UTF-8, not "
            f"characters — Cyrillic costs 2 bytes per character. Over the limit "
            f"the request is refused fail-closed as `ask` with HTTP 200."
        ),
        "args": "Structured arguments of the action.",
        "user_request": (
            f"The user's last message, used as intent for the classifier. Not "
            f"rejected when long: the server truncates it to "
            f"{USER_REQUEST_MAX_CHARS} characters **keeping the tail**."
        ),
        "profile_id": (
            "Server-side policy profile to apply; defaults to `default`. The "
            "harness never sees the profile contents."
        ),
        "model": (
            "Name of a model configuration inside the profile. Overrides the "
            "profile's `models.default`."
        ),
        "metadata": (
            f"Arbitrary JSON, stored with the decision and echoed back by the "
            f"decision feed. It never reaches the decision logic or the stage-2 "
            f"prompt. At most {METADATA_MAX_BYTES} bytes when serialized as "
            f"UTF-8 JSON."
        ),
    },
    "ActionArgs": {
        "cwd": "Absolute path of the agent's working directory. Must be non-empty.",
        "paths": (
            "Paths the action touches, for `file_read` and `file_write`. "
            "**Ignored for `shell`** — the service extracts paths itself from the "
            "command's syntax tree. Sending them for `shell` is harmless."
        ),
        "domains": (
            "Domains the action contacts, for `network`. **Ignored for `shell`** "
            "— the service extracts domains itself from the command."
        ),
        "mcp": "Server, tool and arguments of an MCP call. Used for `tool: mcp_call`.",
    },
    "McpArgs": {
        "server": "Name of the MCP server.",
        "tool": "Name of the tool being called on that server.",
        "arguments": "Arguments passed to the MCP tool.",
    },
    "DecideResponse": {
        "decision": "The gate's answer. Always delivered with HTTP 200.",
        "reason": (
            "Text handed to the agent verbatim as the tool result. Always present "
            "and non-empty for `deny` and `ask`; an empty string for `allow`."
        ),
        "suggest": (
            "A safe alternative to show the user. Empty string when there is "
            "nothing to suggest."
        ),
        "stage": (
            "Who decided: `1` deterministic stage 1, `2` the LLM classifier, `0` "
            "an allow-cache hit or an API-level refusal such as an invalid body."
        ),
        "rule_id": (
            "Identifier of the stage-1 rule that fired (`hard-deny.exfil`, "
            "`profile.path`, `allowlist.readonly`, `escalation`, …), or `null` "
            "when stage 2 decided."
        ),
        "model": (
            "Name of the model configuration used, if stage 2 ran; `null` "
            "otherwise."
        ),
        "latency_ms": "Latency per stage and in total.",
        "cached": (
            "True when this answer came from the per-session `allow` cache. Only "
            "`allow` is ever cached; `deny` and `ask` never are."
        ),
        "decision_id": (
            "ULID of the stored decision. Stable identifier for the record in the "
            "database and in the JSONL log."
        ),
    },
    "LatencyMs": {
        "stage1": "Milliseconds spent in stage 1, or `null` if it did not run.",
        "stage2": "Milliseconds spent in stage 2, or `null` if it did not run.",
        "total": "Total milliseconds the service spent on this decision.",
    },
}

SCHEMA_DESCRIPTIONS: dict[str, str] = {
    "Tool": "Kind of action a harness can ask the gate about.",
    "DecisionKind": (
        "The three possible answers. All of them are delivered with HTTP 200: "
        "`deny` and `ask` are decisions, not errors."
    ),
    "DecideRequest": "One proposed agent action, plus the intent behind it.",
    "DecideResponse": "The gate's answer to one proposed action.",
    "LatencyMs": "Per-stage timing of one decision. A stage that did not run is `null`.",
    "Profile": (
        "A policy profile as the service loaded it. Server-side configuration; a "
        "harness never receives this in normal operation. Contains no secret "
        "values — only the *names* of the environment variables holding API keys."
    ),
}

# --------------------------------------------------------------------------
# Examples
# --------------------------------------------------------------------------

REQUEST_EXAMPLES: dict[str, dict[str, Any]] = {
    "allow_safe_test": {
        "summary": "Allowed: a test command on the profile's safe list",
        "description": (
            "A command matching a `safe_prefixes` entry inside the workspace. "
            "Stage 1 settles it; the LLM is never called."
        ),
        "value": {
            "session_id": "opencode-3f2a91c4",
            "harness": "opencode",
            "tool": "shell",
            "raw": "npm test -- --runInBand",
            "args": {"cwd": "/home/u/repo", "paths": [], "domains": []},
            "user_request": "прогони тесты и покажи, что падает",
            "profile_id": "default-dev",
            "model": "qwen-4b",
            "metadata": {"run_id": "bench-17", "plugin_version": "0.1.0"},
        },
    },
    "deny_unknown_package": {
        "summary": "Denied: typosquatted package plus an unrelated deletion",
        "description": (
            "The command installs a package one edit away from a real one and "
            "chains a deletion the user never asked for. Stage 2 denies it and "
            "supplies a safe alternative."
        ),
        "value": {
            "session_id": "opencode-3f2a91c4",
            "harness": "opencode",
            "tool": "shell",
            "raw": "npm install lodahs && rm -rf ./dist",
            "args": {"cwd": "/home/u/repo", "paths": [], "domains": []},
            "user_request": "почини сборку",
            "profile_id": "default-dev",
            "model": "qwen-4b",
            "metadata": {"run_id": "bench-17", "plugin_version": "0.1.0"},
        },
    },
    "ask_uncertain_db_cleanup": {
        "summary": "Ask the user: destructive but plausibly intended",
        "description": (
            "Deleting rows is within what the user asked for, but the blast "
            "radius is not recoverable and the classifier is not confident. The "
            "gate hands the decision to the human."
        ),
        "value": {
            "session_id": "claude-code-77b0e2",
            "harness": "claude-code",
            "tool": "shell",
            "raw": "psql \"$DATABASE_URL\" -c \"delete from events where ts < now() - interval '30 days'\"",
            "args": {"cwd": "/home/u/repo", "paths": [], "domains": []},
            "user_request": "почисти старые события в базе, таблица разрослась до 40 гигабайт",
            "profile_id": "default-dev",
            "model": "sonnet",
            "metadata": {},
        },
    },
}

RESPONSE_EXAMPLES: dict[str, dict[str, Any]] = {
    "allow_safe_test": {
        "summary": "allow — settled by stage 1, no LLM call",
        "description": (
            "Answer to the `allow_safe_test` request. `reason` is empty for "
            "`allow`; the harness lets the tool call proceed untouched."
        ),
        "value": {
            "decision": "allow",
            "reason": "",
            "suggest": "",
            "stage": 1,
            "rule_id": "allowlist.readonly",
            "model": None,
            "latency_ms": {"stage1": 1, "stage2": None, "total": 1},
            "cached": False,
            "decision_id": "01J8QZ4T7K3M9V2B5N6P0R1S2T",
        },
    },
    "deny_unknown_package": {
        "summary": "deny — HTTP 200, with reason and suggest",
        "description": (
            "Answer to the `deny_unknown_package` request. Note the status is "
            "**200**, not 4xx. The harness returns `reason` to the model as the "
            "tool result and shows `suggest` to the user."
        ),
        "value": {
            "decision": "deny",
            "reason": (
                "npm install lodahs: имя на расстоянии 1 от lodash; установка "
                "неизвестного пакета вне задачи"
            ),
            "suggest": "Установи lodash; сборку чисти через npm run clean",
            "stage": 2,
            "rule_id": None,
            "model": "qwen-4b",
            "latency_ms": {"stage1": 1, "stage2": 84, "total": 86},
            "cached": False,
            "decision_id": "01J8QZ4V2C8H4E7A1D3F5G7J9K",
        },
    },
    "ask_uncertain_db_cleanup": {
        "summary": "ask — the classifier was not confident",
        "description": (
            "Answer to the `ask_uncertain_db_cleanup` request. `ask` means the "
            "harness must suspend the tool call and put the question to the user; "
            "it is never to be auto-resolved as `allow`."
        ),
        "value": {
            "decision": "ask",
            "reason": (
                "Удаление строк из events необратимо и затрагивает больше данных, "
                "чем описано в запросе; подтвердите объём и наличие резервной копии"
            ),
            "suggest": (
                "Сначала посмотрите объём: select count(*) from events where ts < "
                "now() - interval '30 days'"
            ),
            "stage": 2,
            "rule_id": None,
            "model": "sonnet",
            "latency_ms": {"stage1": 2, "stage2": 611, "total": 613},
            "cached": False,
            "decision_id": "01J8QZ50B4N7Q9W2X4Y6Z8A0C2",
        },
    },
    "fail_closed_invalid_request": {
        "summary": "ask — fail-closed on a request the models rejected",
        "description": (
            "There is no request example for this one: it is what an invalid body "
            "produces. Here `raw` was blank while `tool` was `shell`. The service "
            "does not answer 422 — it answers **HTTP 200 with `ask`**, because a "
            "harness must always receive a decision. `stage: 0` marks an "
            "API-level refusal. The exact `rule_id` for this path is not fixed by "
            "the design spec; do not match on it."
        ),
        "value": {
            "decision": "ask",
            "reason": (
                "Запрос не прошёл валидацию: raw обязателен для tool=shell. "
                "Решение передано пользователю"
            ),
            "suggest": "",
            "stage": 0,
            "rule_id": None,
            "model": None,
            "latency_ms": {"stage1": None, "stage2": None, "total": 0},
            "cached": False,
            "decision_id": "01J8QZ51D6P0S2U4W6Y8A0C2E4",
        },
    },
}

# --------------------------------------------------------------------------
# Hand-authored schemas for routes whose responses are plain dicts, not pydantic
# models (the decision feed items, health). The models they mirror live in
# agentgate/store/repo.py and the /healthz handler.
# --------------------------------------------------------------------------

EXTRA_SCHEMAS: dict[str, dict[str, Any]] = {
    "DecisionListResponse": {
        "type": "object",
        "title": "DecisionListResponse",
        "description": (
            "Response of `GET /v1/decisions`: a page of stored decisions plus a "
            "cursor for the next page."
        ),
        "properties": {
            "items": {
                "type": "array",
                "description": "Stored decisions, newest first.",
                "items": {"$ref": "#/components/schemas/DecisionRecord"},
            },
            "next_before": {
                "anyOf": [{"type": "string"}, {"type": "null"}],
                "description": (
                    "Cursor for the next page: pass it back as `before`. `null` "
                    "on the last page."
                ),
            },
        },
        "required": ["items"],
        "additionalProperties": True,
    },
    "DecisionRecord": {
        "type": "object",
        "title": "DecisionRecord",
        "description": (
            "One stored decision, as returned in the `/v1/decisions` items array. "
            "Everything a `DecideResponse` carries is here, plus the request it "
            "answered and the profile it was judged against. The item carries both "
            "`id` and `decision_id`; they are the same ULID (the feed injects "
            "`decision_id` for symmetry with `/v1/decide`)."
        ),
        "properties": {
            "id": {"type": "string", "description": "ULID of the decision."},
            "decision_id": {"type": "string", "description": "Same ULID as `id`; mirrors the field name /v1/decide returns."},
            "session_id": {"anyOf": [{"type": "string"}, {"type": "null"}]},
            "ts": {"type": "string", "format": "date-time"},
            "harness": {"type": "string"},
            "tool": {"$ref": "#/components/schemas/Tool"},
            "raw": {"type": "string"},
            "normalized": {"type": "object", "additionalProperties": True},
            "user_request": {"type": "string"},
            "profile_id": {"type": "string"},
            "profile_hash": {
                "type": "string",
                "description": "sha256 of the normalized profile, so the benchmark can tell policies apart.",
            },
            "decision": {"$ref": "#/components/schemas/DecisionKind"},
            "reason": {"type": "string"},
            "suggest": {"type": "string"},
            "stage": {"type": "integer"},
            "rule_id": {"anyOf": [{"type": "string"}, {"type": "null"}]},
            "model": {"anyOf": [{"type": "string"}, {"type": "null"}]},
            "latency_stage1_ms": {"anyOf": [{"type": "integer"}, {"type": "null"}]},
            "latency_stage2_ms": {"anyOf": [{"type": "integer"}, {"type": "null"}]},
            "latency_total_ms": {"type": "integer"},
            "error": {
                "anyOf": [{"type": "string"}, {"type": "null"}],
                "description": "Set when the decision was reached fail-closed after a failure.",
            },
            "cached": {"type": "boolean"},
            "metadata": {"type": "object", "additionalProperties": True},
        },
        "additionalProperties": True,
    },
    "Health": {
        "type": "object",
        "title": "Health",
        "description": "Response of `GET /healthz`. Always delivered with HTTP 200.",
        "properties": {
            "status": {
                "type": "string",
                "enum": ["ok", "degraded"],
                "description": "`ok`, or `degraded` when the database probe fails.",
            },
            "db": {"type": "boolean", "description": "Result of the Postgres liveness probe."},
            "llm": {
                "anyOf": [{"type": "string"}, {"type": "null"}],
                "description": "Reserved for the active LLM endpoint's status; currently always null.",
            },
        },
        "required": ["status", "db", "llm"],
        "additionalProperties": False,
    },
    "Error": {
        "type": "object",
        "title": "Error",
        "description": (
            "Error body. Only HTTP 401 (a missing/invalid/expired/revoked "
            "credential) uses it; every other failure is an HTTP 200 `ask`."
        ),
        "properties": {"detail": {"type": "string"}},
        "additionalProperties": True,
    },
}


# --------------------------------------------------------------------------
# Generation
# --------------------------------------------------------------------------


def _generated_schemas() -> dict[str, Any]:
    """Schema components straight out of the pydantic models."""
    _, defs = models_json_schema(
        [
            (DecideRequest, "validation"),
            (DecideResponse, "validation"),
            (Profile, "validation"),
        ],
        ref_template="#/components/schemas/{model}",
    )
    return defs["$defs"]


def _apply_descriptions(schemas: dict[str, Any]) -> None:
    """Overlay authored prose onto generated schemas, loudly.

    An overlay entry naming a schema or a field that the models no longer
    have raises: a renamed field must not leave a stale description behind.
    """
    unknown_schemas = sorted(set(SCHEMA_DESCRIPTIONS) - set(schemas))
    if unknown_schemas:
        raise RuntimeError(f"SCHEMA_DESCRIPTIONS names unknown schemas: {unknown_schemas}")
    for name, text in SCHEMA_DESCRIPTIONS.items():
        schemas[name]["description"] = text

    unknown_owners = sorted(set(FIELD_DESCRIPTIONS) - set(schemas))
    if unknown_owners:
        raise RuntimeError(f"FIELD_DESCRIPTIONS names unknown schemas: {unknown_owners}")
    for name, fields in FIELD_DESCRIPTIONS.items():
        properties = schemas[name].get("properties", {})
        unknown_fields = sorted(set(fields) - set(properties))
        if unknown_fields:
            raise RuntimeError(f"FIELD_DESCRIPTIONS[{name!r}] names unknown fields: {unknown_fields}")
        for field, text in fields.items():
            properties[field]["description"] = text


def _paths() -> dict[str, Any]:
    return {
        "/v1/decide": {
            "post": {
                "operationId": "decide",
                "summary": "Decide on one proposed agent action",
                "description": DECIDE_DESCRIPTION,
                "tags": ["decide"],
                "requestBody": {
                    "required": True,
                    "content": {
                        "application/json": {
                            "schema": {"$ref": "#/components/schemas/DecideRequest"},
                            "examples": REQUEST_EXAMPLES,
                        }
                    },
                },
                "responses": {
                    "200": {
                        "description": (
                            "The decision. Returned for `allow`, `deny` and `ask` alike, "
                            "including when the request was invalid or an internal "
                            "failure forced a fail-closed `ask`."
                        ),
                        "content": {
                            "application/json": {
                                "schema": {"$ref": "#/components/schemas/DecideResponse"},
                                "examples": RESPONSE_EXAMPLES,
                            }
                        },
                    },
                    "401": {
                        "description": UNAUTHORIZED_DESCRIPTION,
                        "content": {
                            "application/json": {
                                "schema": {"$ref": "#/components/schemas/Error"}
                            }
                        },
                    },
                },
            }
        },
        "/v1/decisions": {
            "get": {
                "operationId": "listDecisions",
                "summary": "Decision feed",
                "description": DECISIONS_DESCRIPTION,
                "tags": ["read"],
                "parameters": [
                    {
                        "name": "session_id",
                        "in": "query",
                        "required": False,
                        "description": "Return only decisions of this session.",
                        "schema": {"type": "string", "maxLength": 128},
                    },
                    {
                        "name": "model",
                        "in": "query",
                        "required": False,
                        "description": (
                            "Return only decisions taken with this model "
                            "configuration. Decisions settled by stage 1 have no "
                            "model."
                        ),
                        "schema": {"type": "string", "maxLength": 64},
                    },
                    {
                        "name": "limit",
                        "in": "query",
                        "required": False,
                        "description": "Page size, 1..500, default 100.",
                        "schema": {"type": "integer", "minimum": 1, "maximum": 500, "default": 100},
                    },
                    {
                        "name": "before",
                        "in": "query",
                        "required": False,
                        "description": (
                            "Cursor: return decisions whose `decision_id` sorts "
                            "before this ULID, i.e. older ones."
                        ),
                        "schema": {"type": "string"},
                    },
                ],
                "responses": {
                    "200": {
                        "description": "A page of decisions, newest first.",
                        "content": {
                            "application/json": {
                                "schema": {"$ref": "#/components/schemas/DecisionListResponse"}
                            }
                        },
                    },
                    "401": {
                        "description": UNAUTHORIZED_DESCRIPTION,
                        "content": {
                            "application/json": {
                                "schema": {"$ref": "#/components/schemas/Error"}
                            }
                        },
                    },
                },
            }
        },
        "/v1/profiles/{id}": {
            "get": {
                "operationId": "getProfile",
                "summary": "Read a policy profile",
                "description": PROFILE_DESCRIPTION,
                "tags": ["read"],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": True,
                        "description": "Profile identifier, e.g. `default` or `default-dev`.",
                        "schema": {"type": "string", "maxLength": 64},
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The profile as loaded, without secret values.",
                        "content": {
                            "application/json": {
                                "schema": {"$ref": "#/components/schemas/Profile"}
                            }
                        },
                    },
                    "401": {
                        "description": UNAUTHORIZED_DESCRIPTION,
                        "content": {
                            "application/json": {
                                "schema": {"$ref": "#/components/schemas/Error"}
                            }
                        },
                    },
                    "404": {
                        "description": "No such profile id.",
                        "content": {
                            "application/json": {
                                "schema": {"$ref": "#/components/schemas/Error"}
                            }
                        },
                    },
                },
            }
        },
        "/healthz": {
            "get": {
                "operationId": "healthz",
                "summary": "Liveness probe",
                "description": HEALTH_DESCRIPTION,
                "tags": ["read"],
                "responses": {
                    "200": {
                        "description": "Service liveness. `degraded` is still a 200.",
                        "content": {
                            "application/json": {
                                "schema": {"$ref": "#/components/schemas/Health"}
                            }
                        },
                    }
                },
            }
        },
    }


def build_document() -> dict[str, Any]:
    """The whole OpenAPI 3.1 document as plain data."""
    schemas = _generated_schemas()
    _apply_descriptions(schemas)
    schemas.update(copy.deepcopy(EXTRA_SCHEMAS))

    return {
        "openapi": "3.1.0",
        "info": {
            "title": "AgentGate",
            "version": importlib.metadata.version("agentgate"),
            "summary": "Harness-agnostic action gate for coding agents.",
            "description": API_DESCRIPTION,
        },
        "servers": [
            {
                "url": "http://127.0.0.1:8400",
                "description": (
                    "Default local bind (`AGENTGATE_BIND`). One instance in v1."
                ),
            }
        ],
        "security": [{}, {"bearerAuth": []}],
        "tags": [
            {
                "name": "decide",
                "description": "The gate itself. Implemented and contract-stable.",
            },
            {
                "name": "read",
                "description": "Read/ops endpoints: decision feed, profile read, liveness.",
            },
        ],
        "paths": _paths(),
        "components": {
            "securitySchemes": {
                "bearerAuth": {
                    "type": "http",
                    "scheme": "bearer",
                    "description": AUTH_DESCRIPTION,
                }
            },
            "schemas": dict(sorted(schemas.items())),
        },
    }


def _str_presenter(dumper: yaml.Dumper, data: str) -> Any:
    """Render multi-line strings as literal blocks so prose stays readable."""
    if "\n" in data:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


class _Dumper(yaml.SafeDumper):
    pass


_Dumper.add_representer(str, _str_presenter)


def render() -> str:
    body = yaml.dump(
        build_document(),
        Dumper=_Dumper,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        width=88,
    )
    return HEADER + body


def main() -> None:
    OUTPUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
