"""Write ../contracts/openapi.yaml — the document the service itself serves.

Summaries, descriptions and examples live on the routes and the models (see
agentgate.api.app and agentgate.api.schemas); this script only renders what
`app.openapi()` returns, so the published contract cannot drift from the code
that answers the calls.

Run:  cd service && uv run python scripts/export_openapi.py
Test: tests/test_contracts.py asserts the committed YAML equals the freshly
      generated document.
"""

import asyncio
from pathlib import Path
from typing import Any

import httpx
import yaml

from agentgate.bootstrap import build_service
from agentgate.config import Settings
from agentgate.engine.decision import Decision
from agentgate.session.memory import InMemorySessionStateStore

OUTPUT = Path(__file__).resolve().parents[2] / "contracts" / "openapi.yaml"

HEADER = """\
# Generated by service/scripts/export_openapi.py — do not edit by hand.
# Every part of it comes from the running service: the routes in
# service/agentgate/api/app.py and the pydantic models they use.
# Regenerate:  cd service && uv run python scripts/export_openapi.py
# service/tests/test_contracts.py fails if this file and the service disagree.
"""


class _NoStoredSessions(InMemorySessionStateStore):
    """Session store for a documentation build: there is nothing to restore."""

    async def restore(self) -> None:
        return None


class _NoWriter:
    """Decision sink for a documentation build: nothing is decided."""

    async def write(self, decision: Decision) -> None:
        return None


async def _document() -> dict[str, Any]:
    """The OpenAPI document, built without touching Postgres or the network."""
    settings = Settings(db_url="postgresql+asyncpg://export:export@localhost/export")
    async with httpx.AsyncClient() as http:
        service = await build_service(
            settings, http=http, state_store=_NoStoredSessions(), writer=_NoWriter()
        )
    return service.app.openapi()


def build_document() -> dict[str, Any]:
    return asyncio.run(_document())


def _str_presenter(dumper: yaml.Dumper, data: str) -> Any:
    """Render multi-line strings as literal blocks so prose stays readable."""
    if "\n" in data:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


class _Dumper(yaml.SafeDumper):
    pass


_Dumper.add_representer(str, _str_presenter)


def render() -> str:
    body = yaml.dump(
        build_document(),
        Dumper=_Dumper,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        width=88,
    )
    return HEADER + body


def main() -> None:
    OUTPUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
