"""init

Revision ID: 0001
Revises: 
Create Date: 2026-09-03 15:42:40.966986
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('harness', sa.String(length=64), nullable=False),
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('workspace', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deny_consecutive', sa.Integer(), nullable=False),
    sa.Column('deny_total', sa.Integer(), nullable=False),
    sa.Column('decisions_total', sa.Integer(), nullable=False),
    sa.Column('recent_decisions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('harness', sa.String(length=64), nullable=False),
    sa.Column('tool', sa.String(length=32), nullable=False),
    sa.Column('raw', sa.Text(), nullable=False),
    sa.Column('normalized', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_request', sa.Text(), nullable=False),
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('profile_hash', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=8), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('suggest', sa.Text(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('model_raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_stage1_ms', sa.Integer(), nullable=True),
    sa.Column('latency_stage2_ms', sa.Integer(), nullable=True),
    sa.Column('latency_total_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=64), nullable=True),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decisions_decision_ts', 'decisions', ['decision', 'ts'], unique=False)
    op.create_index('ix_decisions_harness_ts', 'decisions', ['harness', 'ts'], unique=False)
    op.create_index('ix_decisions_metadata', 'decisions', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index('ix_decisions_model_ts', 'decisions', ['model', 'ts'], unique=False)
    op.create_index('ix_decisions_session_ts', 'decisions', ['session_id', 'ts'], unique=False)
    op.create_table('allow_cache',
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('action_hash', sa.String(length=64), nullable=False),
    sa.Column('decision_id', sa.String(length=26), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'action_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allow_cache')
    op.drop_index('ix_decisions_session_ts', table_name='decisions')
    op.drop_index('ix_decisions_model_ts', table_name='decisions')
    op.drop_index('ix_decisions_metadata', table_name='decisions', postgresql_using='gin')
    op.drop_index('ix_decisions_harness_ts', table_name='decisions')
    op.drop_index('ix_decisions_decision_ts', table_name='decisions')
    op.drop_table('decisions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
